"""
Comprehensive type stubs for Krita's Python API.

These stubs enable full type checking of plugin code with ty/basedpyright.
They cover the complete public API surface that plugins can use, including
layer management, document operations, color handling, and brush control.

Note: Krita's Python API is not officially typed. These stubs are
community-maintained and may not cover all methods or be 100% accurate.
"""

from typing import Any, Sequence

# Stub imports for PyQt5 — in a real dev environment, PyQt5 stubs
# would be installed. These minimal stubs prevent ty from erroring.
class _QObject: ...
class _QColor: ...

QObject = _QObject
QColor = _QColor

class InfoObject:
    """InfoObject for export options."""
    def __init__(self) -> None: ...
    def setProperty(self, name: str, value: Any) -> None: ...
    def getProperty(self, name: str) -> Any: ...

class ManagedColor:
    """Managed color with color space awareness."""
    @staticmethod
    def fromQColor(color: Any, canvas: "Canvas") -> "ManagedColor": ...
    def colorForCanvas(self, canvas: "Canvas") -> Any: ...
    def setColor(self, color: Any) -> None: ...
    def color(self) -> Any: ...

class Canvas:
    """Krita canvas view."""
    def document(self) -> "Document": ...
    def view(self) -> "View": ...

class Action:
    """Krita action (menu/toolbar action)."""
    def trigger(self) -> None: ...
    def text(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setShortcut(self, shortcut: str) -> None: ...
    def shortcut(self) -> str: ...

class Node:
    """A layer/node in a Krita document."""
    def name(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def type(self) -> str: ...
    def visible(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def opacity(self) -> float: ...
    def setOpacity(self, opacity: float) -> None: ...
    def locked(self) -> bool: ...
    def setLocked(self, locked: bool) -> None: ...
    def active(self) -> bool: ...
    def setActive(self, active: bool) -> None: ...
    def setPixelData(self, data: bytes, x: int, y: int, width: int, height: int) -> None: ...
    def pixelData(self, x: int, y: int, width: int, height: int) -> bytes: ...
    def projectionPixelData(self, x: int, y: int, width: int, height: int) -> bytes: ...
    def bounds(self) -> Any: ...
    def childNodes(self) -> Sequence["Node"]: ...
    def parentNode(self) -> "Node | None": ...
    def addChildNode(self, node: "Node", above: "Node | None") -> None: ...
    def moveNode(self, node: "Node", above: "Node | None") -> None: ...
    def removeNode(self, node: "Node") -> None: ...
    def duplicate(self) -> "Node": ...
    def mergeDown(self) -> "Node": ...
    def colorSpace(self) -> str: ...
    def inherits(self, type: str) -> bool: ...

class Document:
    """A Krita document (canvas)."""
    def width(self) -> int: ...
    def height(self) -> int: ...
    def resolution(self) -> float: ...
    def name(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def rootNode(self) -> Node: ...
    def activeNode(self) -> Node: ...
    def setActiveNode(self, node: Node) -> None: ...
    def createNode(self, name: str, nodeType: str) -> Node: ...
    def refreshProjection(self) -> None: ...
    def exportImage(self, filename: str, info: InfoObject) -> None: ...
    def setBatchmode(self, batchmode: bool) -> None: ...
    def batchmode(self) -> bool: ...
    def colorDepth(self) -> str: ...
    def colorModel(self) -> str: ...
    def xRes(self) -> float: ...
    def yRes(self) -> float: ...
    def bounds(self) -> Any: ...
    def nodes(self) -> Sequence[Node]: ...
    def addNode(self, node: Node, parent: Node, aboveNode: Node | None = None) -> None: ...
    def removeNode(self, node: Node) -> None: ...
    def flatten(self) -> None: ...
    def mergeNode(self, node: Node) -> None: ...
    def duplicateNode(self, node: Node) -> Node: ...
    def layerCount(self) -> int: ...
    def annotations(self) -> dict[str, dict[str, bytes]]: ...
    def setAnnotation(self, application: str, key: str, value: bytes) -> None: ...
    def annotation(self, application: str, key: str) -> bytes: ...
    def removeAnnotation(self, application: str, key: str) -> None: ...
    def modified(self) -> bool: ...
    def setModified(self, modified: bool) -> None: ...
    def fileName(self) -> str: ...
    def setFileName(self, filename: str) -> None: ...
    def mimeType(self) -> str: ...
    def pixelData(self, x: int, y: int, width: int, height: int) -> bytes: ...
    def setPixelData(self, data: bytes, x: int, y: int, width: int, height: int) -> None: ...
    def projection(self) -> Node: ...
    def waitForDone(self) -> None: ...
    def close(self) -> None: ...

class View:
    """A view of a Krita document."""
    def canvas(self) -> Canvas: ...
    def document(self) -> Document: ...
    def foregroundColor(self) -> ManagedColor: ...
    def setForeGroundColor(self, color: ManagedColor) -> None: ...
    def backgroundColor(self) -> ManagedColor: ...
    def setBackGroundColor(self, color: ManagedColor) -> None: ...
    def setCurrentBrushPreset(self, preset: Any) -> None: ...
    def brushPreset(self) -> Any: ...
    def setBrushSize(self, size: int) -> None: ...
    def brushSize(self) -> int: ...
    def setBrushOpacity(self, opacity: float) -> None: ...
    def brushOpacity(self) -> float: ...
    def setBrushFlow(self, flow: float) -> None: ...
    def brushFlow(self) -> float: ...
    def setBrushHardness(self, hardness: float) -> None: ...
    def brushHardness(self) -> float: ...

class Window:
    """A Krita main window."""
    def activeView(self) -> View | None: ...
    def addView(self, doc: Document) -> None: ...
    def views(self) -> Sequence[View]: ...
    def qwindow(self) -> Any: ...
    def activeDocument(self) -> Document | None: ...

class Resource:
    """A Krita resource (brush preset, pattern, etc.)."""
    def name(self) -> str: ...
    def filename(self) -> str: ...
    def hint(self) -> str: ...

class Extension(QObject):
    """Base class for Krita extensions."""
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def setup(self) -> None: ...
    def createActions(self, window: Window) -> None: ...

class Krita(QObject):
    """Main Krita application singleton."""
    @staticmethod
    def instance() -> "Krita": ...
    def createDocument(
        self,
        width: int,
        height: int,
        name: str,
        colorModel: str = "RGBA",
        colorDepth: str = "U8",
        profile: str = "",
        resolution: float = 300.0,
    ) -> Document: ...
    def openDocument(self, filename: str) -> Document | None: ...
    def activeDocument(self) -> Document | None: ...
    def setActiveDocument(self, doc: Document) -> None: ...
    def documents(self) -> Sequence[Document]: ...
    def activeWindow(self) -> Window | None: ...
    def windows(self) -> Sequence[Window]: ...
    def addExtension(self, extension: Extension) -> None: ...
    def removeExtension(self, extension: Extension) -> None: ...
    def extensions(self) -> Sequence[Extension]: ...
    def resources(self, resourceType: str) -> dict[str, Resource]: ...
    def resource(self, resourceType: str, name: str) -> Resource | None: ...
    def action(self, name: str) -> Action | None: ...
    def actions(self) -> Sequence[Action]: ...
    def notifiers(self) -> Sequence[Any]: ...
    def setBatchmode(self, batchmode: bool) -> None: ...
    def batchmode(self) -> bool: ...
    def refreshCanvas(self) -> None: ...
    def quit(self) -> None: ...
    def readSetting(self, group: str, key: str, defaultValue: Any = None) -> Any: ...
    def writeSetting(self, group: str, key: str, value: Any) -> None: ...
